#!/usr/bin/env bash
# script that displays Best School 10 times
# for the 9th iteration, displays Best School then Hi on a new line.

i=0

while [ $i -le 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
		echo "Best School"
	(( i++ ))
done
