#!/usr/bin/env bash
# displays 4 and then bad luck from China 4th iteration
# displays 9 and then bad luck from Japan 9th iteration
# displays 17 and then bad luck from Italy 17th iteration

i=1

while [ $i -le 20 ]
do
  echo "$i"
  case $i in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( i++ ))
done
